"""Initial baseline migration with indexing and user activation status

Revision ID: b409933ce876
Revises: 
Create Date: 2026-07-01 19:11:25.246999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b409933ce876'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_file_id'), 'document_chunks', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_generated_videos_user_id'), 'generated_videos', ['user_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    
    # Add column as nullable first
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Populate existing users
    op.execute("UPDATE users SET is_active = TRUE")
    # Alter column to be NOT NULL
    op.alter_column('users', 'is_active', nullable=False)
    
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_generated_videos_user_id'), table_name='generated_videos')
    op.drop_index(op.f('ix_document_chunks_source_file_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    # ### end Alembic commands ###
